### ISSUE TITLE
Crash when fetching an envelope in Ruby 2

### ISSUE THREAD

**Issue by orfattal** [nu7hatch/gmail#97]
After upgrading to ruby-2.0.0-p353 from 1.9.3, fetching an envelope crashes. here's the stack when calling `envelope` from rails console:
```
2.0.0p353 :007 > emails.first.envelope
ArgumentError: wrong number of arguments (1 for 0)
	from /Users/orfattal/.rvm/gems/ruby-2.0.0-p353@silo/bundler/gems/gmail-3bb194543c0f/lib/gmail/client/imap_extensions.rb:5:in `msg_att'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:2210:in `numeric_response'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:2152:in `response_untagged'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:2132:in `response'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:2058:in `parse'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:1181:in `get_response'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:1089:in `receive_responses'
	from /Users/orfattal/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/imap.rb:1075:in `block in initialize'
```

**Comment by johnnyshields** [comment]
This is now fixed on master.

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#97
